name: flutter_with_supabase
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  supabase_flutter: ^0.2.12
  get: ^4.6.1
  flutter_dotenv: ^5.0.2
  lottie: ^1.2.2
  logger: ^1.1.0
  flutter_secure_storage: ^5.0.2
  supabase: ^0.2.15


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - .env
    - assets/lottie/




